server:
    port: 8081
spring:
    thymeleaf:
        prefix: file:src/main/resources/templates/
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        hibernate:
            ddl-auto: none  
            #update para que traiga la base de datos y si no existen las tablas las crea
    datasource:
        driver-class-name: org.postgresql.Driver
        #driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:postgresql://ec2-44-195-240-222.compute-1.amazonaws.com:5432/d6dvjr909e38d1
        #url: jdbc:mysql://localhost:3306/p_ventas
        #username: postgres
        #password: 19971231
        username: cqaizmobhbdyzc
        password: 4240a43ea69c0a770d7c46d287dcf0085db9f399a81369098a3c387dab2a258e